### PR TITLE
corrects spelling of breadcrumb

### PR DESCRIPTION
**Pull request by iammikek**

### CODE REVIEW

**Comment by iammikek** [comment]
@jsdecena hi, can you explain why this has been rejected please?

**Comment by jsdecena** [comment]
> @jsdecena hi, can you explain why this has been rejected please?

it is draft PR and the unit test is breaking @iammikek

**Comment by iammikek** [comment]
@jsdecena ok. I'll review the unit test, and push an update when I've checked it.

**Comment by iammikek** [comment]
@jsdecena I've switched to master branch on my fork, which should be the same as yours, and I get broken tests in phpunit.

1) Tests\Unit\Categories\CategoryUnitTest::it_can_create_root_category
ErrorException: compact(): Undefined variable: cover

/Users/mike/Documents/Sites/rd/laracom/project/app/Shop/Categories/Repositories/CategoryRepository.php:83
/Users/mike/Documents/Sites/rd/laracom/project/tests/Unit/Categories/CategoryUnitTest.php:232

2) Tests\Unit\Categories\CategoryUnitTest::it_can_update_child_category_to_root_category
ErrorException: compact(): Undefined variable: cover

/Users/mike/Documents/Sites/rd/laracom/project/app/Shop/Categories/Repositories/CategoryRepository.php:117
/Users/mike/Documents/Sites/rd/laracom/project/tests/Unit/Categories/CategoryUnitTest.php:247

3) Tests\Unit\Categories\CategoryUnitTest::it_can_update_root_category_to_child
ErrorException: compact(): Undefined variable: cover

/Users/mike/Documents/Sites/rd/laracom/project/app/Shop/Categories/Repositories/CategoryRepository.php:117
/Users/mike/Documents/Sites/rd/laracom/project/tests/Unit/Categories/CategoryUnitTest.php:265

--

There were 2 failures:

1) Tests\Feature\Admin\Categories\CategoryFeatureTest::it_can_update_the_category
Expected status code 302 but received 500.
Failed asserting that false is true.

/Users/mike/Documents/Sites/rd/laracom/project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
/Users/mike/Documents/Sites/rd/laracom/project/tests/Feature/Admin/Categories/CategoryFeatureTest.php:61

2) Tests\Unit\Categories\CategoryUnitTest::it_errors_creating_the_category_when_required_fields_are_not_passed
Failed asserting that exception of type "ErrorException" matches expected exception "App\Shop\Categories\Exceptions\CategoryInvalidArgumentException". Message was: "compact(): Undefined variable: slug" at
/Users/mike/Documents/Sites/rd/laracom/project/app/Shop/Categories/Repositories/CategoryRepository.php:83
/Users/mike/Documents/Sites/rd/laracom/project/tests/Unit/Categories/CategoryUnitTest.php:117


This is consistent with behaviour I'm getting within admin and relates to the cover image. With my local install, even though I have linked storage, I'm not seeing any product images. I ran the command to link storage outside of my homestead instance. ssh'ing in , I get '  symlink(): No such file or directory ' if I run it.

In admin, within categories, I was unable to 'resave' a category to change its status without reattaching an image and this throws cover error.

**Pull request closed without merging**
