### PR TITLE
Fix: can't update order status

### PR DESCRIPTION
**Pull request by ysknsid25**
On the Edit Order Status screen, an error occurred when pressing the Update button without changing any values.
The cause was the uniqueness of UpdateOrderStatusRequest. The uniqueness check should have been performed on records other than the ID of the update target, but the uniqueness check was performed on the update target itself.
After the fix, I am running OrderStatusUnitTest.php.
The test on the screen is fine.

### CODE REVIEW

**Review by jsdecena — APPROVED** [review]
Thanks!

**Comment by jsdecena** [comment]
@k-yamasaki-zakisan where is your Dockerfile for apple M1?

**Comment by k-yamasaki-zakisan** [comment]
Hi @jsdecena !

Sorry I don't have this project's Dockerfile for apple M1.
Because I used Intel Mac when I contributed to this project.
 [(PR)](https://github.com/jsdecena/laracom/pull/249/files)

Why did you send me the mention?

Think you!

**Comment by k-yamasaki-zakisan** [comment]
@ysknsid25 
> Is your twitter account perhaps https://twitter.com/k_yamasaki_zaki ?

That's right. 
I'm amazed you found my twitter account😳

> We would love to follow you if you like.

sure, great !!

**Pull request merged**
